### ISSUE TITLE
Please change hidden layers and such parameters to an enum 

### ISSUE THREAD

**Issue by andyblarblar** [ssitu/Neural-Network-Library-Class#1]
This library is seriously impressive, but like please don't use magic strings for parameters. For example:
`String hiddenActivationFunction, String outputActivationFunction, String lossFunction, String optimizer` from the constructor can be changed to enums of the same name. So in the end it would be in the constructor:  `HiddenActivationFunction name, OutputActivationFunction name, LossFunction name, Optimizer name` (replace name obviously). The enum for Optimizer would be: 

`public enum LossFunction{
quadratic,
log,
crossEntropy
}`

Or something to that effect.

**Comment by ssitu** [comment]
I knew using strings was a bit tedious but I couldn't think of a better solution. I think I made the switch correctly but I'm not too sure. Thanks for the suggestion as I completely forgot about enums!

**Comment by andyblarblar** [comment]
No problem, most people in ap java seem to forget about them. Your "switch statements" are fine, but arnt actually switch statements. The switch would look something like:
`switch(funcParam){
case Enum.ENUMNAME: 
          /* do what would be done in the if statement */
          break; 
//rest of cases...
default:
            throw new MyException("oops, no match!");
}`

Wether you do this or stick to your chained ifs is purely up to syntax. Most would reccomend a switch, but it isnt that big of a deal.

**Comment by ssitu** [comment]
Switches look a lot easier to work with when adding new things to them so I switched to that too, thanks again!
